[package]
name = "nock_interpreter"
version = "0.2.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "decrement"
harness = false

[lib]
path = "src/lib.rs"
